#
# muon.yml
# RVO2 Library
#
# SPDX-FileCopyrightText: 2008 University of North Carolina at Chapel Hill
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Please send all bug reports to <geom@cs.unc.edu>.
#
# The authors may be contacted via:
#
# Jur van den Berg, Stephen J. Guy, Jamie Snape, Ming C. Lin, Dinesh Manocha
# Dept. of Computer Science
# 201 S. Columbia St.
# Frederick P. Brooks, Jr. Computer Science Bldg.
# Chapel Hill, N.C. 27599-3175
# United States of America
#
# <https://gamma.cs.unc.edu/RVO2/>
#

# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---
name: muon

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '40 5 * * *'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  muon-build-alpine-amd64:
    name: build alpine linux amd64
    runs-on: ubuntu-latest
    container: alpine:3
    timeout-minutes: 30
    steps:
      - name: setup
        run: |
          apk add -q --no-cache \
            acl-static \
            brotli-static \
            bzip2-static \
            ca-certificates \
            curl-dev \
            curl-static \
            expat-static \
            gcc \
            libarchive-dev \
            libarchive-static \
            libidn2-static \
            libpsl-static \
            libunistring-static \
            lz4-static \
            musl-dev \
            nghttp2-static \
            nghttp3-static \
            ninja \
            openssl-libs-static \
            pkgconf-dev \
            xz-static \
            zlib-static \
            zstd-static
        shell: sh
      - name: build
        run: |
          wget -qO- \
            https://github.com/muon-build/muon/archive/refs/tags/0.5.0.tar.gz \
            | tar -xz -C /tmp
          cd /tmp/muon-0.5.0
          ./bootstrap.sh _bootstrap
          _bootstrap/muon-bootstrap setup \
            -Ddefault_library=static \
            -Dstatic=true \
            _build
          ninja -C _build
        shell: sh
      - name: upload
        uses: actions/upload-artifact@v7
        with:
          name: muon-linux-amd64
          path: /tmp/muon-0.5.0/_build/muon
          retention-days: 1

  muon-build-alpine-arm64:
    name: build alpine linux arm64
    runs-on: ubuntu-24.04-arm
    container: alpine:3
    timeout-minutes: 30
    steps:
      - name: setup
        run: |
          apk add -q --no-cache \
            ca-certificates \
            gcc \
            musl-dev \
            ninja \
            pkgconf-dev
        shell: sh
      - name: build
        run: |
          wget -qO- \
            https://github.com/muon-build/muon/archive/refs/tags/0.5.0.tar.gz \
            | tar -xz -C /tmp
          cd /tmp/muon-0.5.0
          ./bootstrap.sh _bootstrap
          _bootstrap/muon-bootstrap setup \
            -Ddefault_library=static \
            -Dstatic=true \
            _build
          ninja -C _build
        shell: sh
      - name: upload
        uses: actions/upload-artifact@v7
        with:
          name: muon-linux-arm64
          path: /tmp/muon-0.5.0/_build/muon
          retention-days: 1

  muon-fmt:
    name: fmt
    needs: muon-build-alpine-amd64
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: download muon
        uses: actions/download-artifact@v8
        with:
          name: muon-linux-amd64
          path: .
      - name: fmt
        run: |
          install -m 755 muon /usr/local/bin/muon
          find . \( -name 'meson.build' -o -name 'meson.options' \) -print0 \
            | xargs -0 muon fmt -q
        shell: bash

  muon-almalinux:
    name: almalinux amd64
    needs: muon-build-alpine-amd64
    runs-on: ubuntu-latest
    container: almalinux:10
    timeout-minutes: 30
    steps:
      - name: setup
        run: |
          dnf makecache -q --refresh || (sleep 15; dnf makecache -q --refresh)
          dnf install -q -y \
            ca-certificates \
            gcc-c++ \
            git \
            glibc-langpack-en \
            libomp-devel \
            ninja-build \
            pkgconf
          dnf clean all
          rm -rf /var/cache/yum
        shell: bash
      - name: checkout
        uses: actions/checkout@v6
      - name: download muon
        uses: actions/download-artifact@v8
        with:
          name: muon-linux-amd64
          path: .
      - name: build test install
        run: |
          install -m 755 muon /usr/local/bin/muon
          muon setup \
            -Dopenmp=enabled \
            -Dprefix="$(pwd)/_build/install" \
            -Dwerror=true \
            _build
          ninja -C _build
          muon -C _build test -v
          muon -C _build install
        shell: bash

  muon-alpine:
    name: alpine linux amd64
    needs: muon-build-alpine-amd64
    runs-on: ubuntu-latest
    container: alpine:3
    timeout-minutes: 30
    steps:
      - name: setup
        run: |
          apk add -q --no-cache \
            ca-certificates \
            g++ \
            git \
            ninja-build \
            openmp-dev \
            pkgconf
        shell: sh
      - name: checkout
        uses: actions/checkout@v6
      - name: download muon
        uses: actions/download-artifact@v8
        with:
          name: muon-linux-amd64
          path: .
      - name: build test install
        run: |
          install -m 755 muon /usr/local/bin/muon
          muon setup \
            -Dopenmp=enabled \
            -Dprefix="$(pwd)/_build/install" \
            -Dwerror=true \
            _build
          ninja -C _build
          muon -C _build test -v
          muon -C _build install
        shell: sh

  muon-arch:
    name: arch linux amd64
    needs: muon-build-alpine-amd64
    runs-on: ubuntu-latest
    container: archlinux:latest
    timeout-minutes: 30
    steps:
      - name: setup
        run: |
          pacman --needed --noconfirm --noprogressbar -Sy \
            ca-certificates \
            gcc \
            git \
            openmp \
            pkgconf \
            samurai
          rm -rf \
            /var/cache/pacman/pkg/* \
            /var/lib/pacman/sync/*
        shell: bash
      - name: checkout
        uses: actions/checkout@v6
      - name: download muon
        uses: actions/download-artifact@v8
        with:
          name: muon-linux-amd64
          path: .
      - name: build test install
        run: |
          install -m 755 muon /usr/local/bin/muon
          muon setup \
            -Dopenmp=enabled \
            -Dprefix="$(pwd)/_build/install" \
            -Dwerror=true \
            _build
          samu -C _build
          muon -C _build test -v
          muon -C _build install
        shell: bash

  muon-fedora:
    name: fedora linux amd64
    needs: muon-build-alpine-amd64
    runs-on: ubuntu-latest
    container: fedora:44
    timeout-minutes: 30
    steps:
      - name: setup
        run: |
          dnf makecache -q --refresh || (sleep 15; dnf makecache -q --refresh)
          dnf install -q -y \
            ca-certificates \
            gcc-c++ \
            git \
            glibc-langpack-en \
            libomp-devel \
            pkgconf \
            samu
          dnf clean all
          rm -rf /var/cache/yum
        shell: bash
      - name: checkout
        uses: actions/checkout@v6
      - name: download muon
        uses: actions/download-artifact@v8
        with:
          name: muon-linux-amd64
          path: .
      - name: build test install
        run: |
          install -m 755 muon /usr/local/bin/muon
          muon setup \
            -Dopenmp=enabled \
            -Dprefix="$(pwd)/_build/install" \
            -Dwerror=true \
            _build
          samu -C _build
          muon -C _build test -v
          muon -C _build install
        shell: bash

  muon-macos:
    name: macos arm64
    runs-on: macos-26
    timeout-minutes: 30
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: cache homebrew
        uses: actions/cache@v5
        with:
          path: ~/Library/Caches/Homebrew/downloads
          key: ${{ runner.os }}-brew-${{ hashFiles('Brewfile') }}
          restore-keys: |
            ${{ runner.os }}-brew-
      - name: setup
        run: |
          brew update -q
          brew bundle install -q
          brew cleanup -q -s
        env:
          HOMEBREW_NO_ANALYTICS: 1
          HOMEBREW_NO_AUTO_UPDATE: 1
          HOMEBREW_NO_INSTALL_CLEANUP: 1
        shell: zsh -efuo pipefail {0}
      - name: build test install
        run: |
          muon setup \
            -Dopenmp=disabled \
            -Dprefix="$(pwd)/_build/install" \
            -Dwerror=true \
            _build
          samu -C _build
          muon -C _build test -v
          muon -C _build install
        shell: zsh -efuo pipefail {0}

  muon-opensuse:
    name: opensuse leap amd64
    needs: muon-build-alpine-amd64
    runs-on: ubuntu-latest
    container: opensuse/leap:16.0
    timeout-minutes: 30
    steps:
      - name: setup
        run: |
          zypper -n -q ref || (sleep 15; zypper -n -q ref)
          zypper -n -q in --no-recommends \
            ca-certificates \
            gcc-c++ \
            git \
            libomp-devel \
            ninja \
            pkgconf
          zypper -n -q cc -a
        shell: bash
      - name: checkout
        uses: actions/checkout@v6
      - name: download muon
        uses: actions/download-artifact@v8
        with:
          name: muon-linux-amd64
          path: .
      - name: build test install
        run: |
          install -m 755 muon /usr/local/bin/muon
          muon setup \
            -Dopenmp=enabled \
            -Dprefix="$(pwd)/_build/install" \
            -Dwerror=true \
            _build
          ninja -C _build
          muon -C _build test -v
          muon -C _build install
        shell: bash

  muon-ubuntu:
    name: ubuntu amd64
    needs: muon-build-alpine-amd64
    runs-on: ubuntu-latest
    container: ubuntu:24.04
    timeout-minutes: 30
    steps:
      - name: setup
        run: |
          apt-get -qq -o APT::Acquire::Retries=4 update \
            || (sleep 15; apt-get -qq -o APT::Acquire::Retries=4 update)
          apt-get -qq -o APT::Acquire::Retries=4 -o Dpkg::Use-Pty=0 \
              --no-install-recommends install \
            ca-certificates \
            g++ \
            git \
            libomp-dev \
            ninja-build \
            pkgconf
          apt-get -qq -o Dpkg::Use-Pty=0 autoremove
          rm -rf /var/lib/apt/lists/*
        env:
          DEBIAN_FRONTEND: noninteractive
        shell: bash
      - name: checkout
        uses: actions/checkout@v6
      - name: download muon
        uses: actions/download-artifact@v8
        with:
          name: muon-linux-amd64
          path: .
      - name: build test install
        run: |
          install -m 755 muon /usr/local/bin/muon
          muon setup \
            -Dopenmp=enabled \
            -Dprefix="$(pwd)/_build/install" \
            -Dwerror=true \
            _build
          ninja -C _build
          muon -C _build test -v
          muon -C _build install
        shell: bash

  muon-ubuntu-arm64:
    name: ubuntu arm64
    needs: muon-build-alpine-arm64
    runs-on: ubuntu-24.04-arm
    container: ubuntu:24.04
    timeout-minutes: 30
    steps:
      - name: setup
        run: |
          apt-get -qq -o APT::Acquire::Retries=4 update \
            || (sleep 15; apt-get -qq -o APT::Acquire::Retries=4 update)
          apt-get -qq -o APT::Acquire::Retries=4 -o Dpkg::Use-Pty=0 \
              --no-install-recommends install \
            ca-certificates \
            g++ \
            git \
            libomp-dev \
            ninja-build \
            pkgconf
          apt-get -qq -o Dpkg::Use-Pty=0 autoremove
          rm -rf /var/lib/apt/lists/*
        env:
          DEBIAN_FRONTEND: noninteractive
        shell: bash
      - name: checkout
        uses: actions/checkout@v6
      - name: download muon
        uses: actions/download-artifact@v8
        with:
          name: muon-linux-arm64
          path: .
      - name: build test install
        run: |
          install -m 755 muon /usr/local/bin/muon
          muon setup \
            -Dopenmp=enabled \
            -Dprefix="$(pwd)/_build/install" \
            -Dwerror=true \
            _build
          ninja -C _build
          muon -C _build test -v
          muon -C _build install
        shell: bash
